# -*- mode: ruby; -*-

Vagrant.configure('2') do |config|
  config.vm.box = 'ubuntu/trusty64'

  config.vm.provision :shell, path: 'provision.sh', args: `secret mysql`

  config.vm.network :private_network, ip: '192.168.0.2'
end
