# -*- mode: ruby; -*-

Vagrant.configure('2') do |config|
  config.vm.box = 'ubuntu/wily64'

  # Workaround for tty error on Ubuntu
  # See https://github.com/mitchellh/vagrant/issues/1673
  config.ssh.shell = 'bash'

  config.vm.provision :shell, path: 'provision.sh', args: `secret mysql`

  config.vm.network :private_network, ip: '192.168.0.2'
end
